/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the `m' library (-lm). */
/* #undef HAVE_LIBM */

/* Define to 1 if you have the `mysqlclient' library (-lmysqlclient). */
#define HAVE_LIBMYSQLCLIENT 1

/* Define to 1 if you have the `z' library (-lz). */
/* #undef HAVE_LIBZ */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <mod_ssl.h> header file. */
/* #undef HAVE_MOD_SSL_H */

/* Define to 1 if you have the `mysql_real_escape_string' function. */
#define HAVE_MYSQL_REAL_ESCAPE_STRING 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "mod_log_sql"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mod_log_sql 1.100"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mod-log-sql"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.100"

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Define if we want to compile in SSL support. */
/* #undef WANT_SSL_LOGGING */

/* Define to 1 if we are compiling with Apache 1.3.x */
/* #undef WITH_APACHE13 */

/* Define to 1 if we are compiling with Apache 2.0.x */
/* #undef WITH_APACHE20 */

/* Define to 1 if we are compiling with mysql */
#define WITH_MYSQL 1

